services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - 8080:8080
    tty: true
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/workspace
