paths:
  root_dir: /Users/masato/Projects/hydra-dvc-practice
  data_dir: /Users/masato/Projects/hydra-dvc-practice/data
  model_dir: /Users/masato/Projects/hydra-dvc-practice/data
model:
  _target_: sklearn.ensemble.RandomForestClassifier
  n_estimators: 100
  random_state: 42
test_size: 0.2
seed: 42
target: target
scaler:
  _target_: sklearn.preprocessing.StandardScaler
