defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
  root:
    level: DEBUG
  verbose: true
